### ISSUE TITLE
Dev mode doesn't work when adding helm extension

### ISSUE THREAD

**Issue by aureamunoz** [redhat-developer-demos/fantastic-dekorate#3]
When adding the Helm extension from the https://quarkiverse.github.io/quarkiverse-docs/quarkus-helm/dev/index.html, the dev mode does not work anymore and also tests have issues. I've seen some PRs regarding the fact things will change with Dekorate 2.9.0, but for the moment the Helm part is not working as expected for Quarkus. Any idea how we can tweak that to work for Quarkus?

**Comment by ammbra** [comment]
Fixed
