### ISSUE TITLE
Tekton dependency doesn't work in Quarkus pet clinic

### ISSUE THREAD

**Issue by aureamunoz** [redhat-developer-demos/fantastic-dekorate#5]
The Tekton dependency works fine for Spring Boot, however I do not have an idea yet how we can make it work for Quarkus.

**Comment by aureamunoz** [comment]
I have been talking with Ioannis and there is no support for dekorate tekton dependency in Quarkus, this was never made it in main, mostly due to the fact that some belive that tekton resource is not something that should be generated a build time. The right way to do tekton in quarkus should be via cli. So we could possibly create a tekton command but don't think we have the time to do it for Devoxx, so I close this issue.
We need to decide how to aproach it in the talk.
WDYT, @ammbra?

**Comment by ammbra** [comment]
I understand. I can make a Tekton script, but the idea would be to demo the capabilities of Dekorate :). So I think is better if we leave this as a bonus demo 🍡

**Comment by aureamunoz** [comment]
yes, totally agree.

**Comment by ammbra** [comment]
Aligned :)
